services:
  wavelength:
    image: ${DOCKER_REGISTRY-}wavelength
    build:
      context: ./wavelength
      dockerfile: Dockerfile
    container_name: wavelength-flutter
    ports:
      - "${HTTP_PORT}:80"
    restart: unless-stopped